spring.cloud.function:
  compile:
    emailValidation:
      inputType: String
      outputType: Optional<String>
      lambda: |
        (String val) -> {
            if (val.length() <= 1) {
                return Optional.of("Length must be greater than 1 char");
            }
            if (!(val.contains("@"))) {
                return Optional.of("Email must contain @ symbol");
            }
            return Optional.empty();
        }
