validation.rules:
  hasLowerCase:
    in: String
    out: Boolean
    lambda: |
      str -> {
        int cnt = 0;

        for (char c : str.toCharArray()) {
          int n = c - 'a';
            if (n >= 0 && n < 26) {
              return true;
            }
          }
        return false;
      }
